name: Automação de Ponto

on:
  schedule:
    - cron: '0 12 * * 1-5'  # 9h horário de Brasília (UTC-3), apenas dias úteis (segunda a sexta)
    - cron: '0 16 * * 1-5'  # 13h horário de Brasília 
    - cron: '0 17 * * 1-5'  # 14h horário de Brasília
    - cron: '0 21 * * 1-5'  # 18h horário de Brasília
    - cron: '0 1 * * 2-6'   # 22h horário de Brasília
    - cron: '20 1 * * 2-6'
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  bater-ponto:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar Chrome e ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install selenium holidays yagmail webdriver-manager
          pip install --verbose selenium  # Verbose install for debugging
      
      - name: Verificar ambiente
        run: |
          echo "Sistema operacional:"
          uname -a
          echo "Versão do Chrome:"
          google-chrome --version
          echo "Versão do Python:"
          python --version
          echo "Listando pacotes instalados:"
          pip list
          
      - name: Verificar arquivos
        run: |
          echo "Listando arquivos na pasta atual:"
          ls -la
          echo "Verificando conteúdo de run_ponto.py:"
          cat run_ponto.py
          
      - name: Executar automação de ponto
        run: |
          echo "Iniciando automação de ponto..."
          python run_ponto.py
          echo "Código de saída: $?"
          
      - name: Upload de screenshots (para debug)
        if: always()
        uses: actions/upload-artifact@latest
        with:
          name: screenshots
          path: /tmp/*.png