name: Automação de Ponto

on:
  schedule:
    - cron: '0 12 * * 1-5'  # 9h horário de Brasília (UTC-3), apenas dias úteis (segunda a sexta)
    - cron: '0 16 * * 1-5'  # 13h horário de Brasília 
    - cron: '0 17 * * 1-5'  # 14h horário de Brasília
    - cron: '0 21 * * 1-5'  # 18h horário de Brasília
    - cron: '0 1 * * 2-6'  # 22h horário de Brasília

jobs:
  bater-ponto:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar Chrome e ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
          wget -q -O /tmp/chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION"
          CHROMEDRIVER_VERSION=$(cat /tmp/chromedriver_linux64.zip)
          wget -q -O /tmp/chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install selenium holidays yagmail webdriver-manager
          
      - name: Executar automação de ponto
        run: python run_ponto.py
